version: '3.8'

services:

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      .env
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASS}
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres

  redis:
    container_name: redis
    image: redis
    command: redis-server
    ports:
      - 6379:6379
    expose:
      - 6379

volumes:
  db:
    driver: local